### ISSUE TITLE
The extension does not activate on a native Windows host

### ISSUE THREAD

**Issue by KeithMnemonic** [SUSE/open-build-service-connector#13]
Upon activating the extension on Windows 10 with vscode 1.50.1, the following error appears

abstractExtensionService.ts:708 Activating extension 'SUSE.open-build-service-connector' failed: ENOENT: no such file or directory, open 'c:\Users\XXXXXX\AppData\Roaming\Code\logs\20201019T114316\exthost5\SUSE.open-build-service-connector\open-build-service-connector.Mon_Oct_19_2020_11:43:37_GMT-0400_(Eastern_Daylight_Time).log'

The directory exists, but for some reason it is unable to create a log file

[2020-10-19 11:43:37.727] [exthost] [error] Activating extension SUSE.open-build-service-connector failed due to an error:
[2020-10-19 11:43:37.727] [exthost] [error] Error: ENOENT: no such file or directory, open 'c:\Users\XXXXXX\AppData\Roaming\Code\logs\20201019T114316\exthost5\SUSE.open-build-service-connector\open-build-service-connector.Mon_Oct_19_2020_11:43:37_GMT-0400_(Eastern_Daylight_Time).log'
	at Object.openSync (fs.js:440:3)
	at Object.func [as openSync] (electron/js2c/asar.js:140:31)
	at openFile (c:\Users\XXXXX\.vscode\extensions\suse.open-build-service-connector-0.0.4\node_modules\sonic-boom\index.js:53:19)
	at new SonicBoom (c:\Users\XXXXX\.vscode\extensions\suse.open-build-service-connector-0.0.4\node_modules\sonic-boom\index.js:87:5)
	at buildSafeSonicBoom (c:\Users\XXXXXX\.vscode\extensions\suse.open-build-service-connector-0.0.4\node_modules\pino\lib\tools.js:295:18)
	at Function.pino.destination (c:\Users\XXXXX\.vscode\extensions\suse.open-build-service-connector-0.0.4\node_modules\pino\pino.js:210:12)
	at c:\Users\XXXXXX\.vscode\extensions\suse.open-build-service-connector-0.0.4\out\extension.js:72:43
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\XXXXXX\.vscode\extensions\suse.open-build-service-connector-0.0.4\out\extension.js:25:58)

**Comment by dcermak** [comment]
This is a weird error, but I have an idea: could you try to create exactly that file in the exact same location that the extension is using via some other method? Maybe Windows does not like the filename (too long or some special characters or whatnot) and node's FS module (being tailored to Unix-like filesystems and not Windows') reporting a relatively useless/misleading error here.

**Comment by KeithMnemonic** [comment]
I think that is the problem. For example in 

C:\Users\XXXXX\AppData\Roaming\Code\logs\20201020T090825\exthost6\output_logging_20201020T090826

the files present are
1-Microsoft Authentication.txt
2-Git.text
...

and if I manually try and create

C:\Users\XXXXXXX\AppData\Roaming\Code\logs\20201020T090825\exthost6\SUSE.open-build-service-connector\open-build-service-connector.Tue_Oct_20_2020_09:08:51_GMT-0400_(Eastern_Daylight_Time).log

I get an error anout the ":" and than it saves the file as 

open-build-service-connector.Tue_Oct_20_2020_090851_GMT-0400_(Eastern_Daylight_Time).log

so I think you need to fix this data string somehow.
